### ISSUE TITLE
SPF Failing for Pirate Ship

### ISSUE THREAD

**Issue by jdogcoder** [hackclub/dns#1050]
![CleanShot 2024-01-16 at 12 51 58@2x](https://github.com/hackclub/dns/assets/65788728/9331c922-707c-4107-abff-481f01fde914)

**Comment by jdogcoder** [comment]
Happy to take this as it should be an easy PR.

**Comment by reesericci** [comment]
Looking at the hackclub.com SPF record, it's configured to allow Postmark: `include:spf.mtasv.net` (line 30). 

Can I get more context on the failure? Is there any misconfiguration showing up in the Postmark or Pirate Ship dashboard?

**Comment by reesericci** [comment]
@jdogcoder notified me this was resolved in #1051

**Comment by reesericci** [comment]
This is apparently still unsolved as DKIM is not setup to allow for Postmark, and emails are still being sent to spam.

cc @cjdenio
