### ISSUE TITLE
Change branch name to follow other hackclub repos

### ISSUE THREAD

**Issue by hkatzdev** [hackclub/dns#400]
I noticed that this still uses master and not main. Guessing this is an oversight since other hack club repos use main - regardless of the name choice it would probably be best to keep the primary branch name consistent across Hack Club repos to make it easier for maintainers / contributors.

**Comment by iamcpdev** [comment]
I think that legacy repos still use master but are being moved over to main slowly but surely. So eventually all if not most of them will use main.

**Comment by maxwofford** [comment]
Looks like this was closed in https://github.com/hackclub/dns/commit/5b5694bc3e91af4e8d8c411b9b49fd0072dfb19d
