### ISSUE TITLE
Multiple domains?

### ISSUE THREAD

**Issue by DhrumanGupta** [hackclub/dns#650]
Hey!

We have been building a website that would need a backend at this point. We cannot use netlify functions due to their limitations and do not have a domain to use for the backend.
If we were to use our VPS's IP directly, it would give us an issue with SSL, and then making calls on HTTP from HTTPS would give other issues.

I'm opening this issue to ask whether our club can have 1 more subdomain, something like `psn-server`. 
It would be really great if we could!

**Comment by cjdenio** [comment]
👋 Hey! Could you elaborate on why a single domain won't work? A tool like [Certbot](https://certbot.eff.org/) should be able to grab an SSL certificate for you once your domain is pointed to the VPS.

**Comment by DhrumanGupta** [comment]
Sorry, I'll elaborare.
Our frontend is made using next.js, which is deployed on netlify (for it's CDNs and CI/CD). The server (express.js) and the website (next.js) are two different programs, so only one of them can be on the domain we have.

**Comment by cjdenio** [comment]
Oh, that makes sense! You can absolutely set up another subdomain (maybe it could be `server.psn.hackclub.com`, @sampoder thoughts?)

**Comment by sampoder** [comment]
`server.psn.hackclub.com` is a good solution for this, let's go with that!
